name: Make a release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run make

    - name: Remove Settings
      run: rm -rf build/*.json
    
    - name: Compress Artifacts
      run: tar -cvzf apps.tar.gz -C build .

    - name: Upload binaries (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: apps.tar.gz
        path: apps.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
